### ISSUE TITLE
Source files

### ISSUE THREAD

**Issue by Zortex04** [Snorflake/Source-Engine-SDK#1]
Cannot open source file "InputManager.h"
Cannot open source file "hooks.h"

**Comment by Snorflake** [comment]
Forgot to comment them out, solved.

**Comment by Zortex04** [comment]
Another thing
I'm getting this error

unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?	structs\checksum_md5.cpp
I have tried adding it but no change

**Comment by Snorflake** [comment]
try unincluding it. this project is old and I no longer have the source (probably) so I can't help you.
